source 'https://rubygems.org'

gem 'access_control', '0.0.1'
gem 'activemerchant', '1.4.0', :require => 'active_merchant'
gem 'acts-as-taggable-on', '2.0.6'
gem 'acts_as_audited', '1.1.1'
gem 'acts_as_tree', '0.1.1'
gem 'authlogic', '2.1.6'
gem 'backup', '3.0.25'
gem 'cancan', '1.5.1'
gem 'capistrano', '2.15.4'
gem 'capistrano-ext', '1.2.1'
gem 'carmen', '0.2.8'
gem 'compass', '0.12.2', :require => false
gem 'compass-rgbapng', '0.1.1', :require => false
gem 'curb'
gem 'daemons', '1.0.10'
gem 'db-charmer', '1.8.4', :require => 'db_charmer'
gem 'delayed-job-ajaycb', '2.0.10', :require=>'delayed_job'
gem 'easy-prof', '1.0.0', :require=>'easy_prof'
gem 'fastercsv', '1.5.4'
gem 'fastimage'
gem 'fog', '1.4.0'
gem 'formtastic', '1.2.4'
gem 'grouped_validations', '0.2.2'
gem 'hirb'
gem 'i18n', '0.4.1'
gem 'jammit', '0.6.5'
gem 'json', '1.5.1'
gem 'less', '1.2.21'
gem 'mail', '2.4.0'
gem 'mailtrap'
gem 'money', '3.1.5'
gem 'mysql', '2.8.1'
gem 'omniauth' , '1.1.0'
gem 'omniauth-facebook', '1.4.0'
gem 'omniauth-oauth2', '1.0.2'
gem 'omniauth-twitter', '1.0.0'
gem 'omniauth-google-oauth2', '0.2.1'
gem 'omniauth-cas', '1.0.2'
gem 'omniauth-linkedin', '0.1.0'
gem 'paperclip', '2.3.11'
gem 'parallel', '0.5.18'
gem 'php-serialize', '1.1.0', :require => 'php_serialize'
gem 'pony', '1.2'
gem 'premailer', '1.7.3'
gem 'rabl', '0.2.8'
gem 'oj', '2.11.1'
gem 'rails', '2.3.8'
gem 'recaptcha', '0.3.1', :require=>'recaptcha/rails'
gem 'rmagick', '2.13.1', :require=>'RMagick'
gem 'rsolr', '0.12.1'
gem 'rsolr-ext', '0.12.1'
gem 'ruby-rc4','0.1.5', :require => 'rc4'
gem 'sass', '3.2.0.alpha.278'

group :development do
  gem 'ruby-debug', '0.10.4'
end

group :test, :development do
  gem 'factory_girl', '2.3.2'
  gem 'faker'
  gem 'interactive_editor'
  gem 'launchy', '0.3.7'
  gem 'rack-test', '0.5.3'
  gem 'rspec-rails', '1.3.4'
  gem 'spork', '0.8'
  gem 'webrat', '0.7.3'
  gem 'wirble'
end
